blank_issues_enabled: false
contact_links:
  - name: 💬 Questions & Help
    url: https://github.com/AnInsomniacy/motrix-next/discussions
    about: Please ask questions and get help in GitHub Discussions instead of opening an issue.
